version: '3.8'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    ports:
      - 5432:5432
    
volumes:
  database:
