[package]
name = "game-sync-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
actix-web = "4"
actix-rt = "2"
actix-web-validator = "5"

# Data formating / manipulation
serde = { workspace = true }
dotenvy = { workspace = true }
config = "0"
jsonwebtoken = "8"
validator = { version = "0.16", features = ["derive"] }
argon2 = { version = "0", "features" = ["std"] }

# Database
sea-orm = { workspace = true }

# Logging
tracing = "0"
tracing-subscriber = "0"

# Error handling
thiserror = "1"

# Timing
time = { version = "0", features = ["serde", "serde-well-known"] }
