[package]
name = "game-sync-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
actix-web = "4"
actix-rt = "2"

# Data formating
serde = { workspace = true }
dotenvy = { workspace = true }
config = "0"

# Database
sea-orm = { workspace = true }

# Logging
log = "0"
pretty_env_logger = "0"

# Error handling
thiserror = "1"
